
# Superset node configuration
supersetNode:
  strategy:
    type: Recreate
  connections:
    # -- Change in case of bringing your own redis and then also set redis.enabled:false
    redis_host: '{{ .Release.Name }}-redis-headless'
    # redis_password: superset
    redis_port: "6379"
    # You need to change below configuration incase bringing own PostgresSQL instance and also set postgresql.enabled:false
    db_host: ns-ii-tech-dev-pg-srv.postgres.database.azure.com
    db_port: "5432"
    # db_user: 
    db_name: superset
    # db_pass: ""

postgresql:
  ##
  ## Use the PostgreSQL chart dependency.
  ## Set to false if bringing your own PostgreSQL.
  enabled: false

image:
  repository: naturalstate/superset
  tag: dev-test
  pullPolicy: Always