
# Superset node configuration
supersetNode:
  strategy:
    type: Recreate
  connections:
    redis_host: '{{ .Release.Name }}-redis-headless'
    redis_port: "6379"
    db_host: ns-ii-tech-stg-pg-srv.postgres.database.azure.com
    db_port: "5432"
    db_name: superset
 
postgresql:
  enabled: false

image:
  repository: naturalstate/superset
  tag: stg-latest
  pullPolicy: Always

extraEnv:
  SECRETS_STORE_NAME: "superset-keyvault-secrets"
  KEYVAULT_NAME: "ns-ii-tech-stg-aks"
  KEYVAULT_TENANT_ID: "6349bddb-01bf-47e0-a152-aaacc2b44281"
  MANAGED_IDENTITY_ID: "5e551bb9-447c-4ee7-b2cc-5ed4f47992ab"
  KEYVAULT_OBJECTS: |
    array:
      - |
        objectName: ArmTenantID
        objectType: secret
      - |
        objectName: SpClientID
        objectType: secret
      - |
        objectName: SpClientSecret
        objectType: secret