
# Superset node configuration
supersetNode:
  strategy:
    type: Recreate
  connections:
    redis_host: '{{ .Release.Name }}-redis-headless'
    redis_port: "6379"
    db_host: ns-ii-tech-dev-pg-srv.postgres.database.azure.com
    db_port: "5432"
    db_name: superset

postgresql:
  enabled: false

image:
  repository: naturalstate/superset
  tag: dev-latest
  pullPolicy: Always