
# Superset node configuration
supersetNode:
  strategy:
    type: Recreate
  connections:
    redis_host: '{{ .Release.Name }}-redis-headless'
    redis_port: "6379"
    db_host: ns-ii-tech-dev-pg-srv.postgres.database.azure.com
    db_port: "5432"
    db_name: superset

postgresql:
  enabled: false

image:
  repository: naturalstate/superset
  tag: dev-latest
  pullPolicy: Always

extraEnv:
  SECRETS_STORE_NAME: "superset-keyvault-secrets"
  KEYVAULT_NAME: "ns-ii-tech-dev-superset"
  KEYVAULT_TENANT_ID: "ad6b5bd3-4317-4894-956f-ab2201f89390"
  MANAGED_IDENTITY_ID: "b495b6e3-8923-4c95-a725-f194f550c7ea"
  KEYVAULT_OBJECTS: |
    array:
      - |
        objectName: ArmTenantID
        objectType: secret
      - |
        objectName: SpClientID
        objectType: secret
      - |
        objectName: SpClientSecret
        objectType: secret