apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Values.extraEnv.SECRETS_STORE_NAME }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.extraEnv.MANAGED_IDENTITY_ID }}
    keyvaultName: {{ $.Values.extraEnv.KEYVAULT_NAME }}
    objects: {{ $.Values.extraEnv.KEYVAULT_OBJECTS | toYaml | nindent 4 }}
    tenantId: {{ $.Values.extraEnv.KEYVAULT_TENANT_ID }}