name: "Docker Image"
on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        options:
          - stage
        description: "The branch to build"
        required: true
        default: stage
      environment:
        description: "The environment to deploy to"
        type: environment
        default: stg
        required: true
      docker_tag:
        description: "Image TAG"
        type: text
        default: latest
        required: true

env:
  DOCKERHUB_TOKEN: "${{secrets.DOCKERHUB_TOKEN}}"
  DOCKERHUB_USER: "${{secrets.DOCKERHUB_USER}}"
  DOCKERHUB_REPOSITORY: "${{vars.DOCKERHUB_REPOSITORY}}"
  DOCKERFILE_PATH: "."
  TAG: "${{ github.event.inputs.docker_tag }}"

jobs:
  deployment:
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v3

      - name: Build & Push Image
        run: |
          .github/workflows/docker_build.sh -r "$DOCKERHUB_REPOSITORY" -u "$DOCKERHUB_USER" -t "$DOCKERHUB_TOKEN" -T "$TAG" -p "$DOCKERFILE_PATH"
