name: "Superset: Deploy"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        type: environment
        default: dev
        required: true

defaults:
  run:
    working-directory: ".github/workflows"

env:
  TLS_CRT: "${{secrets.TLS_CRT}}"
  TLS_KEY: "${{secrets.TLS_KEY}}"
  KUBERNETES_RESOURCE_GROUP: "${{secrets.KUBERNETES_RESOURCE_GROUP}}"
  KUBERNETES_CLUSTER_NAME: "${{secrets.KUBERNETES_CLUSTER_NAME}}"
  POSTGRES_KEYVAULT: "${{secrets.POSTGRES_KEYVAULT}}"
  app_name: "superset"
  namespace: "superset-stg-namespace"
  helm_release: "superset-release"
  k8s_secret_name: "ingress-tls"
  domain_name: "${{secrets.DOMAIN_NAME}}"
  MAPBOX_API_KEY: "${{secrets.MAPBOX_API_KEY}}"
  SMTP_USER: "${{secrets.SMTP_USER}}"
  SMTP_PASSWORD: "${{secrets.SMTP_PASSWORD}}"
  SMTP_MAIL_FROM: "${{secrets.SMTP_MAIL_FROM}}"


jobs:
  deployment:
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: Get keyvault secrets
        run: |
          echo "DB_HOST=$(./keyvault.sh host $POSTGRES_KEYVAULT)" >> $GITHUB_ENV
          echo "DB_USERNAME=$(./keyvault.sh username $POSTGRES_KEYVAULT)" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(./keyvault.sh password $POSTGRES_KEYVAULT)" >> $GITHUB_ENV

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: "${{ env.KUBERNETES_RESOURCE_GROUP }}"
          cluster-name: "${{ env.KUBERNETES_CLUSTER_NAME }}"

      - name: Create namespace and secret
        run: |
          source ./secrets.sh -n ${{env.namespace}} -s ${{env.k8s_secret_name}} --tls-crt ${{env.TLS_CRT}} --tls-key ${{env.TLS_KEY}}

      - name: Update helm chart and values
        run: |
          source ./deployment.sh
          deploy_superset ${{env.namespace}} ${{env.helm_release}} ${{env.domain_name}} ${{env.k8s_secret_name}} ${{env.DB_HOST}} ${{env.DB_USERNAME}} ${{env.DB_PASSWORD}} ${{env.MAPBOX_API_KEY}} ${{env.SMTP_USER}} ${{env.SMTP_PASSWORD}} ${{env.SMTP_MAIL_FROM}}

